# Site settings
title: TASS
slogan: "Trustworthy & Affordable Software Services"
email: zinatusa@gmail.com
description: >
  TASS has been founded by Dr. Shawon Rahman (Associate Professor of Computer Science, Univ of Hawaii-Hilo) in June 2012. TASS has already established a good reputation in providing higher-quality work, reliability, and fairness within very short time. We have a skilled team of developers who develop various types of Mobile Apps and web-based software including iOS apps, Windows phone, iPad, etc. apps. Currently more than 10 persons are working in our company including two current students and one graduated student from University of Hawaii. Most of our developers have a MS or Ph.D. degree in Computer Science or Software Engineering. Our developers work from Hawaii or mainland USA. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tassusa.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: TASSUSA

# Build settings
markdown: kramdown

# Define custom collections
collections:
  members: # The members of TASS
    output: true

exclude: ["START SERVER", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]