# Site settings
title: TASS
slogan: "Trustworthy & Affordable Software Services"
email: zinatusa@gmail.com
description:  "TASS develops various types of Mobile Apps (iOS apps, Windows phone, iPad, etc), telecommunication software, animation/virtualization, learning games, virtual labs, and web-based software."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tassusa.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: TASSUSA

# Build settings
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: 'http://tassusa.github.io/'
  media: 'media'

# Define custom collections
collections:
  members: # The members of TASS
    output: true

exclude: ["START SERVER", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
